# Generated by Django 5.1.4 on 2024-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Файл видео')),
                ('access_date', models.DateTimeField(verbose_name='Дата доступа к видео')),
                ('week_number', models.PositiveIntegerField(unique=True, verbose_name='Номер недели (URL)')),
            ],
        ),
    ]
